const translations={
ru:{language:'Язык',workspace:'Рабочий список',title:'Материалы для объекта',subtitle:'Соберите заказ, сохраните его и отправьте поставщику.',positions:'позиций',object:'Объект',newOrder:'Новый заказ',objectAddress:'Адрес объекта',addressPlaceholder:'Например, Brīvības iela 120, Rīga',orderName:'Название заказа',orderPlaceholder:'Материалы для перегородок',addMaterial:'Добавить материал',savedCatalog:'Сохранённый каталог',material:'Материал',materialPlaceholder:'Регипс, шпаклёвка, краска…',productCode:'Код товара / штрихкод',codePlaceholder:'Например, 68524992',quantity:'Количество',unit:'Единица',pcs:'шт.',pack:'уп.',depoLink:'Ссылка на товар DEPO (необязательно)',price:'Цена за единицу',add:'Добавить',order:'Заказ',emptyTitle:'Список пока пуст',emptyText:'Добавьте первый материал выше.',save:'Сохранить на устройстве',downloadCsv:'Скачать CSV',printPdf:'Печать / PDF',share:'Отправить',catalog:'Сохранённый каталог',catalogHelp:'Нажмите на товар, чтобы добавить его в форму.',saved:'Заказ сохранён на этом устройстве.',removed:'Позиция удалена.',shared:'Список готов к отправке.',newReady:'Новый заказ готов.',noItems:'Сначала добавьте материалы.',catalogEmpty:'Каталог пуст — сохраните первый заказ.',link:'DEPO',total:'Итого'},
lv:{language:'Valoda',workspace:'Darba saraksts',title:'Materiāli objektam',subtitle:'Sagatavojiet pasūtījumu, saglabājiet un nosūtiet piegādātājam.',positions:'pozīcijas',object:'Objekts',newOrder:'Jauns pasūtījums',objectAddress:'Objekta adrese',addressPlaceholder:'Piemēram, Brīvības iela 120, Rīga',orderName:'Pasūtījuma nosaukums',orderPlaceholder:'Materiāli starpsienām',addMaterial:'Pievienot materiālu',savedCatalog:'Saglabātais katalogs',material:'Materiāls',materialPlaceholder:'Reģipsis, špaktele, krāsa…',productCode:'Preces kods / svītrkods',codePlaceholder:'Piemēram, 68524992',quantity:'Daudzums',unit:'Vienība',pcs:'gab.',pack:'iep.',depoLink:'DEPO preces saite (nav obligāta)',price:'Cena par vienību',add:'Pievienot',order:'Pasūtījums',emptyTitle:'Saraksts ir tukšs',emptyText:'Pievienojiet pirmo materiālu.',save:'Saglabāt ierīcē',downloadCsv:'Lejupielādēt CSV',printPdf:'Drukāt / PDF',share:'Nosūtīt',catalog:'Saglabātais katalogs',catalogHelp:'Nospiediet preci, lai to pievienotu formai.',saved:'Pasūtījums saglabāts šajā ierīcē.',removed:'Pozīcija izdzēsta.',shared:'Saraksts gatavs nosūtīšanai.',newReady:'Jauns pasūtījums gatavs.',noItems:'Vispirms pievienojiet materiālus.',catalogEmpty:'Katalogs ir tukšs — saglabājiet pirmo pasūtījumu.',link:'DEPO',total:'Kopā'},
uk:{language:'Мова',workspace:'Робочий список',title:'Матеріали для об’єкта',subtitle:'Складіть замовлення, збережіть його та надішліть постачальнику.',positions:'позицій',object:'Об’єкт',newOrder:'Нове замовлення',objectAddress:'Адреса об’єкта',addressPlaceholder:'Наприклад, Brīvības iela 120, Rīga',orderName:'Назва замовлення',orderPlaceholder:'Матеріали для перегородок',addMaterial:'Додати матеріал',savedCatalog:'Збережений каталог',material:'Матеріал',materialPlaceholder:'Гіпсокартон, шпаклівка, фарба…',productCode:'Код товару / штрихкод',codePlaceholder:'Наприклад, 68524992',quantity:'Кількість',unit:'Одиниця',pcs:'шт.',pack:'уп.',depoLink:'Посилання на товар DEPO (необов’язково)',price:'Ціна за одиницю',add:'Додати',order:'Замовлення',emptyTitle:'Список поки порожній',emptyText:'Додайте перший матеріал вище.',save:'Зберегти на пристрої',downloadCsv:'Завантажити CSV',printPdf:'Друк / PDF',share:'Надіслати',catalog:'Збережений каталог',catalogHelp:'Натисніть товар, щоб додати його до форми.',saved:'Замовлення збережено на цьому пристрої.',removed:'Позицію видалено.',shared:'Список готовий до надсилання.',newReady:'Нове замовлення готове.',noItems:'Спочатку додайте матеріали.',catalogEmpty:'Каталог порожній — збережіть перше замовлення.',link:'DEPO',total:'Разом'}};
const defaults=['Регипс / Reģipsis','Профиль / Profils','Шпаклёвка / Špaktele','Краска / Krāsa','Валик / Rullītis','Шурупы / Skrūves','Штукатурка / Apmetums'];
const $=id=>document.getElementById(id);let items=[];let lang=localStorage.getItem('kredos_lang')||'ru';
function t(key){return translations[lang][key]||key}function money(v){return new Intl.NumberFormat(lang==='lv'?'lv-LV':lang==='uk'?'uk-UA':'ru-RU',{style:'currency',currency:'EUR'}).format(v)}
function applyLanguage(){$('languageSelect').value=lang;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));render()}
function render(){const list=$('itemsList');list.innerHTML='';$('emptyState').hidden=items.length>0;items.forEach((item,i)=>{const row=document.createElement('div');row.className='item';row.innerHTML=`<div><div class="item-name"></div>${item.code?'<span class="item-code"></span>':''}${item.link?`<a class="item-link" target="_blank" rel="noopener">${t('link')} ↗</a>`:''}</div><div class="item-meta"></div><div class="item-meta"></div><button class="remove" aria-label="Удалить">×</button>`;row.querySelector('.item-name').textContent=item.name;if(item.code)row.querySelector('.item-code').textContent=item.code;if(item.link){const a=row.querySelector('a');a.href=item.link}row.querySelectorAll('.item-meta')[0].textContent=`${item.qty} ${unitLabel(item.unit)}`;row.querySelectorAll('.item-meta')[1].textContent=item.price?money(item.qty*item.price):'—';row.querySelector('.remove').onclick=()=>{items.splice(i,1);render();status(t('removed'))};list.appendChild(row)});$('itemCount').textContent=items.length;$('total').textContent=money(items.reduce((s,x)=>s+(x.price||0)*x.qty,0));persistDraft()}
function unitLabel(unit){return unit==='pcs'?t('pcs'):unit==='pack'?t('pack'):unit}
function status(message){$('status').textContent=message;setTimeout(()=>{if($('status').textContent===message)$('status').textContent=''},3000)}
function orderData(){return{address:$('objectAddress').value.trim(),name:$('orderName').value.trim(),items,updated:new Date().toISOString()}}
function persistDraft(){localStorage.setItem('kredos_order',JSON.stringify(orderData()))}function save(){persistDraft();const catalog=JSON.parse(localStorage.getItem('kredos_catalog')||'[]');items.forEach(x=>{const old=catalog.find(y=>(x.code&&y.code===x.code)||y.name.toLowerCase()===x.name.toLowerCase());if(old)Object.assign(old,{code:x.code,unit:x.unit,link:x.link,price:x.price});else catalog.push({name:x.name,code:x.code,unit:x.unit,link:x.link,price:x.price})});localStorage.setItem('kredos_catalog',JSON.stringify(catalog));status(t('saved'))}
function csv(){if(!items.length)return status(t('noItems'));const rows=[['KREDOS'],[t('objectAddress'),$('objectAddress').value],[t('orderName'),$('orderName').value],[],[t('material'),t('productCode'),t('quantity'),t('unit'),t('price'),t('depoLink')],...items.map(x=>[x.name,x.code||'',x.qty,unitLabel(x.unit),x.price||'',x.link||''])];const content='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));a.download=`kredos-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
function textOrder(){return[`KREDOS — ${$('orderName').value||t('order')}`,`${t('objectAddress')}: ${$('objectAddress').value||'—'}`,'',...items.map((x,i)=>`${i+1}. ${x.name}${x.code?' · '+t('productCode')+': '+x.code:''} — ${x.qty} ${unitLabel(x.unit)}${x.price?' · '+money(x.qty*x.price):''}${x.link?' · '+x.link:''}`),'',`${t('total')}: ${money(items.reduce((s,x)=>s+(x.price||0)*x.qty,0))}`].join('\n')}
function openCatalog(){const catalog=JSON.parse(localStorage.getItem('kredos_catalog')||'[]');const box=$('catalogList');box.innerHTML='';if(!catalog.length){box.textContent=t('catalogEmpty')}catalog.forEach(x=>{const b=document.createElement('button');b.className='catalog-item';b.innerHTML='<span></span><span></span>';b.firstChild.textContent=x.name;b.lastChild.textContent=x.code||'+';b.onclick=()=>{$('itemName').value=x.name;$('itemCode').value=x.code||'';$('itemUnit').value=x.unit;$('itemLink').value=x.link||'';$('itemPrice').value=x.price||'';$('catalogDialog').close()};box.appendChild(b)});$('catalogDialog').showModal()}
$('itemForm').addEventListener('submit',e=>{e.preventDefault();items.push({name:$('itemName').value.trim(),code:$('itemCode').value.trim(),qty:Number($('itemQty').value),unit:$('itemUnit').value,link:$('itemLink').value.trim(),price:Number($('itemPrice').value)||0});e.target.reset();$('itemQty').value=1;render();$('itemName').focus()});
$('languageSelect').onchange=e=>{lang=e.target.value;localStorage.setItem('kredos_lang',lang);applyLanguage()};$('saveBtn').onclick=save;$('csvBtn').onclick=csv;$('printBtn').onclick=()=>{if(items.length)window.print();else status(t('noItems'))};$('shareBtn').onclick=async()=>{if(!items.length)return status(t('noItems'));const text=textOrder();if(navigator.share){await navigator.share({title:'KREDOS',text})}else{await navigator.clipboard.writeText(text)}status(t('shared'))};$('openCatalogBtn').onclick=openCatalog;$('closeCatalogBtn').onclick=()=>$('catalogDialog').close();$('newOrderBtn').onclick=()=>{if(confirm(t('newOrder')+'?')){items=[];$('objectAddress').value='';$('orderName').value='';localStorage.removeItem('kredos_order');render();status(t('newReady'))}};
$('objectAddress').addEventListener('input',persistDraft);$('orderName').addEventListener('input',persistDraft);
const saved=JSON.parse(localStorage.getItem('kredos_order')||'null');if(saved){items=saved.items||[];$('objectAddress').value=saved.address||'';$('orderName').value=saved.name||''}const datalist=$('materials');defaults.forEach(x=>{const o=document.createElement('option');o.value=x;datalist.appendChild(o)});applyLanguage();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
