const translations={
ru:{install:'Установить',workspace:'ЗАКАЗ МАТЕРИАЛОВ',title:'Список для объекта',positions:'позиций',object:'Объект',address:'Адрес объекта',addressPh:'Brīvības iela 120, Rīga',listName:'Название списка',listPh:'Основные материалы',addMaterial:'Добавить материал',material:'Название материала',materialPh:'Например, регипс',quantity:'Количество',unit:'Единица',pcs:'шт.',pack:'уп.',code:'Код товара / штрихкод',add:'Добавить',update:'Сохранить',cancel:'Отмена',order:'Список материалов',clear:'Очистить',emptyTitle:'Список пуст',emptyText:'Добавляйте материалы один за другим.',templates:'Шаблоны и отправка',templatePh:'Название шаблона',saveTemplate:'Сохранить как шаблон',save:'Сохранить список',whatsapp:'Отправить в WhatsApp',print:'Печать / PDF',edit:'Редактировать',remove:'Удалить',load:'Загрузить',saved:'Список сохранён на этом устройстве.',templateSaved:'Шаблон сохранён.',templateLoaded:'Шаблон загружен. Измените адрес и количество.',needItems:'Сначала добавьте материалы.',needTemplateName:'Введите название шаблона.',confirmClear:'Очистить весь текущий список?',confirmDeleteTemplate:'Удалить этот шаблон?',installHelp:'На iPhone нажмите «Поделиться», затем «На экран Домой».',soundOn:'Звук включён',soundOff:'Звук выключен'},
lv:{install:'Instalēt',workspace:'MATERIĀLU PASŪTĪJUMS',title:'Objekta saraksts',positions:'pozīcijas',object:'Objekts',address:'Objekta adrese',addressPh:'Brīvības iela 120, Rīga',listName:'Saraksta nosaukums',listPh:'Pamatmateriāli',addMaterial:'Pievienot materiālu',material:'Materiāla nosaukums',materialPh:'Piemēram, reģipsis',quantity:'Daudzums',unit:'Vienība',pcs:'gab.',pack:'iep.',code:'Preces kods / svītrkods',add:'Pievienot',update:'Saglabāt',cancel:'Atcelt',order:'Materiālu saraksts',clear:'Notīrīt',emptyTitle:'Saraksts ir tukšs',emptyText:'Pievienojiet materiālus vienu pēc otra.',templates:'Veidnes un nosūtīšana',templatePh:'Veidnes nosaukums',saveTemplate:'Saglabāt kā veidni',save:'Saglabāt sarakstu',whatsapp:'Nosūtīt WhatsApp',print:'Drukāt / PDF',edit:'Rediģēt',remove:'Dzēst',load:'Ielādēt',saved:'Saraksts saglabāts šajā ierīcē.',templateSaved:'Veidne saglabāta.',templateLoaded:'Veidne ielādēta. Mainiet adresi un daudzumu.',needItems:'Vispirms pievienojiet materiālus.',needTemplateName:'Ievadiet veidnes nosaukumu.',confirmClear:'Notīrīt visu pašreizējo sarakstu?',confirmDeleteTemplate:'Dzēst šo veidni?',installHelp:'iPhone: nospiediet “Kopīgot”, pēc tam “Pievienot sākuma ekrānam”.',soundOn:'Skaņa ieslēgta',soundOff:'Skaņa izslēgta'},
uk:{install:'Встановити',workspace:'ЗАМОВЛЕННЯ МАТЕРІАЛІВ',title:'Список для об’єкта',positions:'позицій',object:'Об’єкт',address:'Адреса об’єкта',addressPh:'Brīvības iela 120, Rīga',listName:'Назва списку',listPh:'Основні матеріали',addMaterial:'Додати матеріал',material:'Назва матеріалу',materialPh:'Наприклад, гіпсокартон',quantity:'Кількість',unit:'Одиниця',pcs:'шт.',pack:'уп.',code:'Код товару / штрихкод',add:'Додати',update:'Зберегти',cancel:'Скасувати',order:'Список матеріалів',clear:'Очистити',emptyTitle:'Список порожній',emptyText:'Додавайте матеріали один за одним.',templates:'Шаблони та надсилання',templatePh:'Назва шаблону',saveTemplate:'Зберегти як шаблон',save:'Зберегти список',whatsapp:'Надіслати у WhatsApp',print:'Друк / PDF',edit:'Редагувати',remove:'Видалити',load:'Завантажити',saved:'Список збережено на цьому пристрої.',templateSaved:'Шаблон збережено.',templateLoaded:'Шаблон завантажено. Змініть адресу та кількість.',needItems:'Спочатку додайте матеріали.',needTemplateName:'Введіть назву шаблону.',confirmClear:'Очистити весь поточний список?',confirmDeleteTemplate:'Видалити цей шаблон?',installHelp:'На iPhone натисніть «Поділитися», потім «На початковий екран».',soundOn:'Звук увімкнено',soundOff:'Звук вимкнено'}};
const $=id=>document.getElementById(id);let lang=localStorage.getItem('kredos_lang')||'ru';let items=[];let editIndex=-1;let installPrompt=null;let soundOn=localStorage.getItem('kredos_sound')!=='off';
function t(key){return translations[lang][key]||key}function unitLabel(unit){return unit==='pcs'?t('pcs'):unit==='pack'?t('pack'):unit}function clone(v){return JSON.parse(JSON.stringify(v))}
function beep(kind='ok'){if(!soundOn)return;try{const ctx=new(window.AudioContext||window.webkitAudioContext)();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=kind==='delete'?190:kind==='edit'?420:620;gain.gain.setValueAtTime(.045,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.11);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.11)}catch{}}
function status(message){$('status').textContent=message;setTimeout(()=>{if($('status').textContent===message)$('status').textContent=''},3000)}
function draft(){return{address:$('objectAddress').value.trim(),name:$('orderName').value.trim(),items,updated:new Date().toISOString()}}function persist(){localStorage.setItem('kredos_order',JSON.stringify(draft()))}
function applyLanguage(){$('languageSelect').value=lang;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));$('soundBtn').textContent=soundOn?'🔊':'🔇';renderItems();renderTemplates()}
function renderItems(){const list=$('itemsList');list.innerHTML='';$('emptyState').hidden=items.length>0;items.forEach((item,i)=>{const row=document.createElement('div');row.className='item';row.innerHTML='<div><div class="item-name"></div><span class="item-code"></span></div><div class="item-qty"></div><div class="item-unit"></div><div class="item-actions"><button class="edit">✎</button><button class="delete">×</button></div>';row.querySelector('.item-name').textContent=item.name;const code=row.querySelector('.item-code');if(item.code)code.textContent=item.code;else code.hidden=true;row.querySelector('.item-qty').textContent=item.qty;row.querySelector('.item-unit').textContent=unitLabel(item.unit);const edit=row.querySelector('.edit');edit.title=t('edit');edit.onclick=()=>startEdit(i);const del=row.querySelector('.delete');del.title=t('remove');del.onclick=()=>{items.splice(i,1);if(editIndex===i)cancelEdit();renderItems();beep('delete')};list.appendChild(row)});$('itemCount').textContent=items.length;persist()}
function startEdit(i){editIndex=i;const item=items[i];$('itemName').value=item.name;$('itemQty').value=item.qty;$('itemUnit').value=item.unit;$('itemCode').value=item.code||'';$('addBtn').textContent=t('update');$('cancelEditBtn').hidden=false;$('itemName').focus();beep('edit')}
function cancelEdit(){editIndex=-1;$('itemForm').reset();$('itemQty').value=1;$('addBtn').textContent=t('add');$('cancelEditBtn').hidden=true}
function templates(){return JSON.parse(localStorage.getItem('kredos_templates')||'[]')}function storeTemplates(value){localStorage.setItem('kredos_templates',JSON.stringify(value))}
function renderTemplates(){const box=$('templatesList');box.innerHTML='';templates().forEach(template=>{const row=document.createElement('div');row.className='template';row.innerHTML='<div><strong></strong><small></small></div><button class="template-load"></button><button class="template-delete">×</button>';row.querySelector('strong').textContent=template.name;row.querySelector('small').textContent=`${template.items.length} ${t('positions')}`;const load=row.querySelector('.template-load');load.textContent=t('load');load.onclick=()=>{items=clone(template.items);$('orderName').value=template.name;$('templateName').value=template.name;cancelEdit();renderItems();status(t('templateLoaded'));beep()};row.querySelector('.template-delete').onclick=()=>{if(!confirm(t('confirmDeleteTemplate')))return;storeTemplates(templates().filter(x=>x.id!==template.id));renderTemplates();beep('delete')};box.appendChild(row)})}
function orderText(){return[`KREDOS — ${$('orderName').value||t('order')}`,`${t('address')}: ${$('objectAddress').value||'—'}`,'',...items.map((x,i)=>`${i+1}. ${x.name} — ${x.qty} ${unitLabel(x.unit)}${x.code?' — '+t('code')+': '+x.code:''}`)].join('\n')}
function buildPrint(){const locale=lang==='lv'?'lv-LV':lang==='uk'?'uk-UA':'ru-RU';$('printDate').textContent=new Intl.DateTimeFormat(locale,{day:'2-digit',month:'long',year:'numeric'}).format(new Date());$('printOrderName').textContent=$('orderName').value.trim()||t('order');$('printAddress').textContent=$('objectAddress').value.trim()||'—';$('printMaterialHead').textContent=t('material');$('printCodeHead').textContent=t('code');$('printQtyHead').textContent=t('quantity');$('printFooterCount').textContent=`${items.length} ${t('positions')}`;const body=$('printRows');body.innerHTML='';items.forEach((item,index)=>{const row=document.createElement('tr');[index+1,item.name,item.code||'—',`${item.qty} ${unitLabel(item.unit)}`].forEach(value=>{const cell=document.createElement('td');cell.textContent=value;row.appendChild(cell)});body.appendChild(row)})}
$('itemForm').onsubmit=event=>{event.preventDefault();const item={name:$('itemName').value.trim(),qty:Number($('itemQty').value),unit:$('itemUnit').value,code:$('itemCode').value.trim()};if(editIndex>=0)items[editIndex]=item;else items.push(item);cancelEdit();renderItems();beep();$('itemName').focus()};$('cancelEditBtn').onclick=cancelEdit;
$('objectAddress').oninput=persist;$('orderName').oninput=persist;$('languageSelect').onchange=event=>{lang=event.target.value;localStorage.setItem('kredos_lang',lang);applyLanguage()};
$('soundBtn').onclick=()=>{soundOn=!soundOn;localStorage.setItem('kredos_sound',soundOn?'on':'off');$('soundBtn').textContent=soundOn?'🔊':'🔇';status(soundOn?t('soundOn'):t('soundOff'));beep()};
$('saveBtn').onclick=()=>{persist();status(t('saved'));beep()};$('printBtn').onclick=()=>{if(!items.length)return status(t('needItems'));buildPrint();window.print();beep()};$('whatsappBtn').onclick=()=>{if(!items.length)return status(t('needItems'));window.open(`https://wa.me/?text=${encodeURIComponent(orderText())}`,'_blank','noopener');beep()};
$('clearBtn').onclick=()=>{if(items.length&&confirm(t('confirmClear'))){items=[];cancelEdit();renderItems();beep('delete')}};
$('saveTemplateBtn').onclick=()=>{if(!items.length)return status(t('needItems'));const name=$('templateName').value.trim()||$('orderName').value.trim();if(!name)return status(t('needTemplateName'));const all=templates();const old=all.find(x=>x.name.toLowerCase()===name.toLowerCase());if(old){old.items=clone(items);old.updated=Date.now()}else all.push({id:Date.now(),name,items:clone(items),updated:Date.now()});storeTemplates(all);$('templateName').value=name;renderTemplates();status(t('templateSaved'));beep()};
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else alert(t('installHelp'))};window.addEventListener('appinstalled',()=>{$('installBtn').hidden=true;beep()});
const saved=JSON.parse(localStorage.getItem('kredos_order')||'null');if(saved){items=(saved.items||[]).map(x=>({name:x.name,qty:x.qty,unit:x.unit,code:x.code||''}));$('objectAddress').value=saved.address||'';$('orderName').value=saved.name||''}applyLanguage();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
