const fs=require('node:fs'),test=require('node:test');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {doc,setDoc,getDoc,updateDoc,deleteDoc,serverTimestamp}=require('firebase/firestore');
let env;
test.before(async()=>{env=await initializeTestEnvironment({projectId:'demo-kredos',firestore:{rules:fs.readFileSync('cloud/firestore.rules','utf8')}});});
test.after(async()=>{await env?.cleanup();});
const order=uid=>({name:'Order',address:'Riga',items:[{name:'Knauf',qty:2,unit:'pcs',code:'123',url:''}],state:'new',createdBy:uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),revision:1});
test('database enforces verified owner, read-only users, delegated editing and immediate revocation',async()=>{
 const owner=env.authenticatedContext('owner',{email:'dshtriters@gmail.com',email_verified:true}).firestore();
 const viewer=env.authenticatedContext('viewer',{email:'reader@example.com',email_verified:true,role:'admin'}).firestore();
 const mod=env.authenticatedContext('mod',{email:'mod@example.com',email_verified:true}).firestore();
 const fakeOwner=env.authenticatedContext('fake',{email:'dshtriters@gmail.com',email_verified:false}).firestore();
 const guest=env.unauthenticatedContext().firestore();
 await assertFails(setDoc(doc(fakeOwner,'orders','fake'),order('fake')));
 await assertFails(setDoc(doc(viewer,'orders','viewer'),order('viewer')));
 await assertFails(setDoc(doc(viewer,'moderators','reader@example.com'),{email:'reader@example.com',assignedBy:'viewer',createdAt:serverTimestamp()}));
 await assertSucceeds(setDoc(doc(owner,'orders','one'),order('owner')));
 await assertSucceeds(getDoc(doc(viewer,'orders','one')));
 await assertFails(getDoc(doc(guest,'orders','one')));
 await assertFails(updateDoc(doc(viewer,'orders','one'),{name:'Hacked',revision:2,updatedAt:serverTimestamp()}));
 await assertFails(deleteDoc(doc(viewer,'orders','one')));
 await assertSucceeds(setDoc(doc(owner,'moderators','mod@example.com'),{email:'mod@example.com',assignedBy:'owner',createdAt:serverTimestamp()}));
 await assertFails(setDoc(doc(owner,'moderators','dshtriters@gmail.com'),{email:'dshtriters@gmail.com',assignedBy:'owner',createdAt:serverTimestamp()}));
 await assertSucceeds(setDoc(doc(mod,'orders','two'),order('mod')));
 await assertSucceeds(updateDoc(doc(mod,'orders','one'),{name:'Edited by moderator',revision:2,updatedAt:serverTimestamp()}));
 await assertFails(updateDoc(doc(mod,'orders','one'),{createdBy:'mod',revision:3,updatedAt:serverTimestamp()}));
 await assertFails(updateDoc(doc(mod,'orders','one'),{name:'Stale revision',revision:2,updatedAt:serverTimestamp()}));
 await assertFails(deleteDoc(doc(mod,'orders','one')));
 await assertFails(setDoc(doc(mod,'moderators','other@example.com'),{email:'other@example.com',assignedBy:'mod',createdAt:serverTimestamp()}));
 await assertFails(updateDoc(doc(owner,'orders','one'),{role:'admin',revision:3,updatedAt:serverTimestamp()}));
 await assertSucceeds(deleteDoc(doc(owner,'moderators','mod@example.com')));
 await assertFails(updateDoc(doc(mod,'orders','one'),{name:'Revoked',revision:3,updatedAt:serverTimestamp()}));
 await assertSucceeds(deleteDoc(doc(owner,'orders','one')));
});
